services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
